version: "3.8"

services:
  # -----------------------
  # auth service pgdb
  # -----------------------
  serviceauthmngdb:
    image: mongo
    container_name: service-auth-mngdb
    restart: always
    env_file:
      - .env
    ports:
      - '6000:27017'
    volumes:
      - service_auth_mng:/data/db

  # -----------------------
  # auth service pgdb
  # -----------------------
  serviceauthpgdb:
    image: postgres
    container_name: service-auth-pgdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER_AUTH}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_AUTH}
      - POSTGRES_DB=${POSTGRES_DB_AUTH}
    ports:
      - "5434:5432"
    volumes:
      - service_auth_data:/var/lib/postgresql/data
  # -----------------------
  # auth service
  # -----------------------
  service-auth-app:
    environment:
      - ENVIRONMENT=SERVICE_DEV
    container_name: service-auth-app
    image: auth-app-img-dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - serviceauthpgdb
      - serviceauthmngdb
    volumes:
      - ./:/app
    ports:
      - 4004:8004

volumes:
  service_auth_data:
  service_auth_mng:
